title: "Autonomous Ground Robot in Unstructured Environments: How Far Have We Come?)"
venue: RA-L
year: 2024
authors: []
abstract: Journal of Field Robotics (JFR) 2026：Survey Paper about Autonomous
  Ground Robot System in Unstructured Off-Road Environments
tags: []
repo: https://github.com/chaytonmin/Survey-Autonomous-Driving-in-Unstructured-Off-Road-Environments
arxiv: https://arxiv.org/abs/2410.07701
date_added: 2026-04-09
